#!/bin/bash

export AS_MAIN_DIR=/media/pi/remainder/NR/JavaTesting

export AS_LANDING_PAD_DIR=$AS_MAIN_DIR/LandingPad
export AS_SCRIPTS_DIR=$AS_MAIN_DIR/Scripts
export AS_LIB_DIR=$AS_MAIN_DIR/Lib
export AS_WORKING_DIR=$AS_MAIN_DIR/SysWorking
export AS_SCRUBBED_DIR=$AS_MAIN_DIR/SysScrubbed
export AS_DATA_DIR=$AS_MAIN_DIR/Data
export AS_LOGS_DIR=$AS_MAIN_DIR/Logs



