#!/bin/bash



#java -cp "/media/pi/remainder/NR/JavaTesting/Lib/*" com.ec.nr.App

#java -cp ../Lib/2015-MP3-Processor-1.0-SNAPSHOT.jar:../Lib/activation-1.1.jar:../Lib/aopalliance-1.0.jar:../Lib/commons-codec-1.3.jar:../Lib/commons-logging-1.2.jar:../Lib/core-1.47.1.jar:../Lib/google-api-client-1.19.1.jar:../Lib/google-api-services-oauth2-v2-rev86-1.19.1.jar:../Lib/google-http-client-1.18.0-rc.jar:../Lib/google-http-client-jackson2-1.19.0.jar:../Lib/google-oauth-client-1.18.0-rc.jar:../Lib/google-oauth-client-java6-1.18.0-rc.jar:../Lib/google-oauth-client-jetty-1.11.0-beta.jar:../Lib/guava-13.0.1.jar:../Lib/guava-jdk5-13.0.jar:../Lib/httpclient-4.0.1.jar:../Lib/httpcore-4.0.1.jar:../Lib/jackson-core-2.1.3.jar:../Lib/jetty-6.1.26.jar:../Lib/jetty-util-6.1.26.jar:../Lib/jsr305-1.3.7.jar:../Lib/junit-3.8.1.jar:../Lib/log4j-1.2.17.jar:../Lib/log4j2.xml:../Lib/log4j-api-2.1.jar:../Lib/log4j-core-2.1.jar:../Lib/log4j.xml:../Lib/mail-1.4.jar:../Lib/nr2015.jar:../Lib/servlet-api-2.5-20081211.jar:../Lib/spring-aop-4.1.4.RELEASE.jar:../Lib/spring-beans-4.1.4.RELEASE.jar:../Lib/SpringBeans.xml:../Lib/spring-context-4.1.4.RELEASE.jar:../Lib/spring-core-4.1.4.RELEASE.jar:../Lib/spring-expression-4.1.4.RELEASE.jar:../Lib/TestShell.jar:../Lib/userInfo.json com.ec.nr.App 

java -Dlog4j.configurationFile=/media/pi/remainder/NR/JavaTesting/Lib/log4j2.xml -cp /media/pi/remainder/NR/JavaTesting/Lib/userInfo.json:/media/pi/remainder/NR/JavaTesting/Lib/2015-MP3-Processor-1.0-SNAPSHOT.jar:/media/pi/remainder/NR/JavaTesting/Lib/activation-1.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/aopalliance-1.0.jar:/media/pi/remainder/NR/JavaTesting/Lib/commons-codec-1.3.jar:/media/pi/remainder/NR/JavaTesting/Lib/commons-logging-1.2.jar:/media/pi/remainder/NR/JavaTesting/Lib/core-1.47.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-api-client-1.19.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-api-services-oauth2-v2-rev86-1.19.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-http-client-1.18.0-rc.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-http-client-jackson2-1.19.0.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-oauth-client-1.18.0-rc.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-oauth-client-java6-1.18.0-rc.jar:/media/pi/remainder/NR/JavaTesting/Lib/google-oauth-client-jetty-1.11.0-beta.jar:/media/pi/remainder/NR/JavaTesting/Lib/guava-13.0.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/guava-jdk5-13.0.jar:/media/pi/remainder/NR/JavaTesting/Lib/httpclient-4.0.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/httpcore-4.0.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/jackson-core-2.1.3.jar:/media/pi/remainder/NR/JavaTesting/Lib/jetty-6.1.26.jar:/media/pi/remainder/NR/JavaTesting/Lib/jetty-util-6.1.26.jar:/media/pi/remainder/NR/JavaTesting/Lib/jsr305-1.3.7.jar:/media/pi/remainder/NR/JavaTesting/Lib/junit-3.8.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/log4j-1.2.17.jar:/media/pi/remainder/NR/JavaTesting/Lib/log4j-api-2.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/log4j-core-2.1.jar:/media/pi/remainder/NR/JavaTesting/Lib/mail-1.4.jar:/media/pi/remainder/NR/JavaTesting/Lib/nr2015.jar:/media/pi/remainder/NR/JavaTesting/Lib/servlet-api-2.5-20081211.jar:/media/pi/remainder/NR/JavaTesting/Lib/spring-aop-4.1.4.RELEASE.jar:/media/pi/remainder/NR/JavaTesting/Lib/spring-beans-4.1.4.RELEASE.jar:/media/pi/remainder/NR/JavaTesting/Lib/spring-context-4.1.4.RELEASE.jar:/media/pi/remainder/NR/JavaTesting/Lib/spring-core-4.1.4.RELEASE.jar:/media/pi/remainder/NR/JavaTesting/Lib/spring-expression-4.1.4.RELEASE.jar:/media/pi/remainder/NR/JavaTesting/Lib/TestShell.jar com.ec.nr.App /media/pi/remainder/NR/JavaTesting/Lib/SpringBeans.xml

javaExit=$?

echo "java exit code:" $javaExit

exit $javaExit
